apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-info-ingress
  namespace: development
  labels:
    app: pod-info
spec:
  ingressClassName: traefik
  rules:
  - host: pod-info.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pod-info-service
            port:
              number: 80
